### PR TITLE
convert-image-format@el-amine-404: Add exec perms and set default window size

### PR DESCRIPTION
**Pull request by anaximeno**
I got this error while testing (this text is in portuguese but it basically says that it failed to execute the script):

Captura de ecrã de 2024-07-01 00-21-50

It was fixed by adding execution permissions to the script.

---

I also set a default size of the zenity window as 640x320:

- Before
Captura de ecrã de 2024-07-01 00-50-09

- After
Captura de ecrã de 2024-07-01 00-49-22

cc @el-amine-404

### CODE REVIEW

**Comment by anaximeno** [comment]
@rcalixte it seems that the execution permission issue happens with other actions that don't have the exec permission like the calculate-sha*sum@rcalixte actions

**Comment by rcalixte** [comment]
> @rcalixte it seems that the execution permission issue happens with other actions that don't have the exec permission like the calculate-sha*sum@rcalixte actions, can you try to see if you can reproduce it? Try reinstalling these actions and use them.

I've been meaning to push the change for this. It's all scripts as of Cinnamon 6.2. PR coming right now.

**Review by rcalixte — APPROVED** [review]

**Comment by rcalixte** [comment]
@el-amine-404 Pushing this through for the permissions fix. Feel free to open another pull request if you want to modify the window parameters.

**Comment by anaximeno** [comment]
> That ended up being a big bang all at once but we should now have permissions appropriately set everywhere. Only scripts that may need to execute are executable and all other files that aren't intended to be executable are not. (The only drawback is that there are going to be a **LOT** of updates of Spices.)

Great, I already received some updates :), this may get them ready for Mint 22.

**Pull request merged**
