### PR TITLE
Do not use OS user for ssh login in open-in-remote-terminal

### PR DESCRIPTION
**Pull request by zrpfpr**
Update action "open-in-remote-terminal" and try to extract user from the connection path part instead using the OS current user, because in most cases will be different.

### CODE REVIEW

**Comment by rcalixte** [comment]
cc @hsbasu @mamolinux

**Comment by hsbasu** [comment]
@zrpfpr I'm super busy now. I'll check this when I get time. Thanks for the PR.

**Comment by rcalixte** [comment]
> @rcalixte You can ask for review using the **Reviewers** options from the right panel in a PR.

Unfortunately, this isn't supported unless you have write access to the repository. Only **Assignees** functions as a loose field. (I briefly tested to see if anything had changed and it hasn't.)

**Review by hsbasu — CHANGES_REQUESTED** [review]
Actually, there is no point in using `os.environ` when the remote user name is different from local. The best way to overcome this is to involve the user.

I suggest the following changes from line 38 to 44
```$python
# in case path contains the home folder and the user, try to use it instead OS user
home, sep, user = remote_path.partition('/')

# remote user from path. If not present, ask for username
if user:
    remote_user = user
else:
        dialog_cmd = ['zenity --entry', '--text "Username:" --title "Enter remote username"']
        remote_user = subprocess.check_output(dialog_cmd, shell=True).decode("utf-8", "strict").strip('\n')
```

**Comment by zrpfpr** [comment]
Good approach. But maybe we can go futher... 

After some research, I can see that if the user check the option to store the credentials when connect to the server at first time, these data will be present in the gnome keyring. In that escenario we can get it using seahorse, but it implies some new dependencies (and the user implication maybe to install them using pip). In that case, it will be no necessary prompt the username first with that dialog (and the password later in terminal), simplyfing the login process. How do you see that possibility? 

I am new with python, but I think that could be possible, because we can get the password from the terminal using secret-tool. More research is needed. Thanks!

**Comment by hsbasu** [comment]
> Good approach. But maybe we can go futher...
> 
> After some research, I can see that if the user check the option to store the credentials when connect to the server at first time, these data will be present in the gnome keyring. In that escenario we can get it using seahorse, but it implies some new dependencies (and the user implication maybe to install them using pip). In that case, it will be no necessary prompt the username first with that dialog (and the password later in terminal), simplyfing the login process. How do you see that possibility?
> 
> I am new with python, but I think that could be possible, because we can get the password from the terminal using secret-tool. More research is needed. Thanks!

The idea is good. But asking for username and handling/storing passwords are two different regimes. As the later involves knowledge on computer security and I have zero knowledge, I would like to avoid implementing that now. Also I personally want to keep things simple. The goal of this action is to give `nemo` the equal footing with `nautilus` and `caja`. Both of them implements **open in remote terminal**. Both of them ask for password if you are not using ssh key. So, right now I would like to receive feedback from other users before implementing any new feature.

**Comment by zrpfpr** [comment]
Add the changes to adapt the PR using your proposal (add support for the new PO messages) .Thanks, @hsbasu

**Comment by hsbasu** [comment]
@rcalixte LGTM. Can be merged.

**Review by rcalixte — APPROVED** [review]

**Pull request merged**
