### PR TITLE
Update Portuguese translation

### PR DESCRIPTION
**Pull request by hugok79**
Portuguese translation update

Change the file from **pt_PT** to **pt** to follow Portuguese consistency: https://translations.launchpad.net/linuxmint/latest/+lang/pt

However, the language code is maintained

### CODE REVIEW

**Review by rcalixte — APPROVED** [review]

**Comment by rcalixte** [comment]
You can rename an existing file in a repository with `git mv {old_name} {new_name}`. As you saw when you opened the pull request, it identified that the file was renamed and modified. Hopefully this saves you an extra step in the future.

**Comment by rcalixte** [comment]
I'm curious though. I'm assuming there are differences for pt_PT and pt_BR? Should they stay separate?

**Comment by hugok79** [comment]
Yes, they should be kept apart. Portuguese is the official language spoken in Portugal. There are some differences. In Brazil, Portuguese is spoken, but as you would expect and since Brazil is a country with a lot of cultural diversity, there tends to be a lot of deviation from correct Portuguese and the result is words adopted by Brazilians that are simply derived from English or are simply invented and are not in the Portuguese dictionary.

**Comment by rcalixte** [comment]
In that case, it's probably best to keep the language codes and the file names matching too.

**Pull request merged**
