### PR TITLE
peazip-add-to-archive@xszabo3: change symlink, update readme instructions

### PR DESCRIPTION
**Pull request by xszabo3**
Changed symlink - this will be consistent across actions
Updated readme instructions

### CODE REVIEW

**Review by rcalixte — APPROVED** [review]

**Comment by xszabo3** [comment]
@rcalixte I just noticed, the symlink is missing from the published zip. Are symlinks unsupported?

**Comment by rcalixte** [comment]
> @rcalixte I just noticed, the symlink is missing from the published zip. Are symlinks unsupported?

Let me test, I thought they were but maybe something is changing in the packaging if the symlinks can't be resolved.

**Comment by rcalixte** [comment]
It looks likes the symlinks are not being packaged. Apologies. This is a learning experience for me as well.

**Comment by xszabo3** [comment]
@rcalixte Good to know. I will replace them with icons then...

**Pull request merged**
