### PR TITLE
peazip-flatpak-extract@xszabo3: Extract... action for PeaZip(Flatpak)

### PR DESCRIPTION
**Pull request by xszabo3**
This adds Extract... to the context menu.

### CODE REVIEW

**Review by rcalixte — APPROVED** [review]

**Comment by rcalixte** [comment]
@xszabo3 I've noticed inconsistency in the image structure you're using for the icon/symlink and also the metadata. Just something to be mindful of when users search the UI. (You should do a search on your end now that these are public. Ideally, they are synchronized in the UI.)

**Comment by xszabo3** [comment]
@rcalixte Thanks again.
The icon inconsistency is present only for the Convert action - that one is missing from the flatpak files, I will try to search for it... maybe it can be found elsewhere.
I will checked the metadata, they seem to follow the same style, can you expand a bit on that?
The only thing that is definitely inconsistent is the UUID. Should I change that?

**Comment by rcalixte** [comment]
> I will checked the metadata, they seem to follow the same style, can you expand a bit on that?

I might have misread but the names didn't appear to be consistent. I can double-check. My memory could be foggy here too. 😅



> The only thing that is definitely inconsistent is the UUID. Should I change that?

No, it's too late for that now and it's not terribly relevant.

**Comment by xszabo3** [comment]
@rcalixte The name was changed 3 times yesterday, so I'm not surprised about the confusion :)

**Pull request merged**
