### PR TITLE
Rename zh to zh_CN

### PR DESCRIPTION
**Pull request by rcalixte**
Renaming zh to zh_CN to differentiate from zh_HK and zh_TW

cc @aaasoft

### CODE REVIEW

**Comment by aaasoft** [comment]
Hi,after rename zh to zh_CN，My Linux Mint now just display english not chinese now.Do you known what's wrong?

图片

**Comment by rcalixte** [comment]
Were the downloads previously translated? As far as I understand, you wouldn't see those translated until they are installed? Can you share the output of:

```bash
echo "LANG: ${LANG} LANGUAGE: ${LANGUAGE}"
```

**Comment by aaasoft** [comment]
Yes,before zh change to zh_CN,Actions in downloads tab was translated.
After zh change to zh_CN,I wouldn't see those translated until they are installed.

image

**Comment by rcalixte** [comment]
> Yes,before zh change to zh_CN,Actions in downloads tab was translated.

That's interesting because the compiled translations aren't installed unless they are downloaded. And the update shouldn't have affected any locally compiled existing translations. You can see the partial translations after the title and the author ("by" to "作者") but those translations are provided outside of the Spices themselves.

**Comment by aaasoft** [comment]
I found a screenshot at 2024/05/30. Extensions was translated before installed.Actions was same to Extensions.

微信图片_20240626224127

**Comment by rcalixte** [comment]
> I found a screenshot at 2024/05/30. Extensions was translated before installed.Actions was same to Extensions.

Can you share the output of:

```bash
ls ~/.local/share/locale/zh*/*
```

**Comment by aaasoft** [comment]
> > I found a screenshot at 2024/05/30. Extensions was translated before installed.Actions was same to Extensions.
> 
> Can you share the output of:
> 
> ```shell
> ls ~/.local/share/locale/zh*/*
> ```

图片

**Comment by aaasoft** [comment]
Actions info was loaded from [https://cinnamon-spices.linuxmint.com/json/actions.json](https://cinnamon-spices.linuxmint.com/json/actions.json)
There is zh_CN translation in json file.but not display in UI.may be it's a cinnamon bug there.

图片


图片

**Comment by aaasoft** [comment]
I confirm it's a bug [there](https://github.com/linuxmint/cinnamon/blob/f08780cbf7bdf682f40ee140b58c041dbd746ee4/files/usr/share/cinnamon/cinnamon-settings/bin/ExtensionCore.py#L36).

`
LANGUAGE_CODE = "C"
try:
    LANGUAGE_CODE = locale.getlocale()[0].split("_")[0]
except:
    pass
`

with current python code.LANGUAGE_CODE will always be zh not zh_CN。

**Comment by rcalixte** [comment]
> with current python code.LANGUAGE_CODE will always be zh not zh_CN。

Good catch. This is likely breaking every language configured like this. Let's see if we can get it fixed for all languages.

**Comment by aaasoft** [comment]
I saw your pull request.Well done.

**Comment by rcalixte** [comment]
> I saw your pull request.Well done.

Thanks to you for finding the bug. This is impacting tons of languages.

**Pull request merged**
