### PR TITLE
peazip-add-to-archive@xszabo3: add the icon back

### PR DESCRIPTION
**Pull request by xszabo3**

### CODE REVIEW

**Comment by rcalixte** [comment]
@xszabo3 Do you want to combine these into the same pull request since they are all logically consistent?

**Review by rcalixte — APPROVED** [review]

**Comment by xszabo3** [comment]
@rcalixte Sorry, I just noticed the message. I already opened a separate one...

**Comment by rcalixte** [comment]
> @rcalixte Sorry, I just noticed the message. I already opened a separate one...

Do you want to consolidate there?

**Comment by xszabo3** [comment]
@rcalixte No, I think these 3 actions should be done, I will add the remaining ones tomorrow

**Pull request merged**
