### PR TITLE
multiple: Several German translation

### PR DESCRIPTION
**Pull request by R3tr0BoiDX**
I've added the German translations for:

* cinnamon-system-settings @100savage 
* file-shredder @CZmisaCZ 
* paste-into-file @anaximeno 
* restart-cinnamon @claudiux 
* vscode-launcher @vajdao 

Potentially adding more at some later point.

### CODE REVIEW

**Review by rcalixte — APPROVED** [review]

**Comment by JokerGermany** [comment]
The translation don't work for me for file-shredder
could it be because the file is a .pot file and not a .po file?
I renamed it, and it still don't work

**Comment by rcalixte** [comment]
> could it be because the file is a .pot file and not a .po file?

Correct. This will be corrected shortly. Apologies for the oversight.



> I renamed it, and it still don't work

Translations need to be compiled and then installed. This happens when they are installed or updated.

**Comment by rcalixte** [comment]
> The translation don't work for me for file-shredder

Can you update your Actions and try again?

**Comment by R3tr0BoiDX** [comment]
> > could it be because the file is a .pot file and not a .po file?
> 
> Correct. This will be corrected shortly. Apologies for the oversight.
> 
> > I renamed it, and it still don't work
> 
> Translations need to be compiled and then installed. This happens when they are installed or updated.

My bad, I'm sorry. This is new to me. Can you maybe point me to where I can learn how to do it right?

**Comment by rcalixte** [comment]
> My bad, I'm sorry. This is new to me. Can you maybe point me to where I can learn how to do it right?

Take a look at what it took to fix in #457. Also, use the scripts to test locally until you have the process perfected. One thing we can do to help is catch some of these in the validation step as well.

**Pull request merged**
