### PR TITLE
open-with-vscode: allows open file(s) or folder(s) with Visual Studio Code

### PR DESCRIPTION
**Pull request by kirill-d-lappo**
* allows open file(s) or folder(s) with Visual Studio Code
* icon is taken from https://code.visualstudio.com/brand

### CODE REVIEW

**Comment by rcalixte** [comment]
@kirill-d-lappo Isn't this already possible from within Nemo?

From my machine:


The top option can be configured from within Settings -> Preferred Applications.

**Comment by kirill-d-lappo** [comment]
> @kirill-d-lappo Isn't this already possible from within Nemo?
> 
> From my machine:
> 
> 
> The top option can be configured from within Settings -> Preferred Applications.

It is.

But that action allows you to open multiple selected files or folders. Also it can open  folder that is currently opened in Nemo.

And it's a bit easier to click because the action is not placed in nested menu. It could be handy if you use vscode frequently.

I created that action years ago, just decided to share.

**Comment by rcalixte** [comment]
> But that action allows you to open multiple selected files or folders. Also it can open folder that is currently opened in Nemo.

Multiple selection for files is already supported and I'm not seeing support from VS Code on my local machine to open directories. (It just opens a blank canvas.)

> And it's a bit easier to click because the action is not placed in nested menu. It could be handy if you use vscode frequently.

You can configure your defaults to modify the menu:



> I created that action years ago, just decided to share.

Does that mean that you don't have duplicate menu items on your machine? Can you share what you're seeing on your end?

**Comment by kirill-d-lappo** [comment]
@rcalixte,

> Multiple selection for files is already supported and I'm not seeing support from VS Code on my local machine to open directories. (It just opens a blank canvas.)

VS Code opens selected folders in a new workspace
folder

> You can configure your defaults to modify the menu

That's true, tbh, I never gave a thought about that.

> Does that mean that you don't have duplicate menu items on your machine? Can you share what you're seeing on your end?

Well, I have them both, of course.
context-menu

Ok, I can see that the most popular use cases are already here, so it is an overhead to create another action. Let's close it

**Comment by kirill-d-lappo** [comment]
yeah, functionality duplication, sure
https://github.com/linuxmint/cinnamon-spices-actions/commit/817ff3a6eee13fc6be9107f9a7de1ea043a7886a

**Comment by rcalixte** [comment]
> yeah, functionality duplication, sure [817ff3a](https://github.com/linuxmint/cinnamon-spices-actions/commit/817ff3a6eee13fc6be9107f9a7de1ea043a7886a)

Apologies if these feel like the same thing. If you look closely at the Selection parameter, it does not show the Action on a selection, i.e. it only works when right-clicking in an empty space. It directly inverts the duplicated functionality here.

**Pull request closed without merging**
