### PR TITLE
link-target-to-tab@mdpenguin & search-path-to-tab@mdpenguin: initial commit

### PR DESCRIPTION
**Pull request by mdpenguin**
Initial commit of Open Link Target Path in New Tab action.  Action opens the path to the target of a symbolic link in a new tab.

Initial commit of Open Path from Search in New Tab action.  Action opens the path to a file selected in Nemo search results in a new tab.

### CODE REVIEW

**Comment by claudiux** [comment]
`$ ./validate-spice search-path-to-tab@mdpenguin`
returns:
```
[search-path-to-tab@mdpenguin] Error during validation: Unable to read: search-path-to-tab@mdpenguin.nemo_action.in

Error(s) found! Once you fix the issue(s), please re-run 'validate-spice <uuid>' to check for further errors.
```

`$ ./validate-spice link-target-to-tab@mdpenguin`
returns:
```
[link-target-to-tab@mdpenguin] Error during validation: Unable to read: link-target-to-tab@mdpenguin.nemo_action.in

Error(s) found! Once you fix the issue(s), please re-run 'validate-spice <uuid>' to check for further errors.
```

**Comment by mdpenguin** [comment]
@claudiux, the issue seems to be that I haven't put an underscore before `Name` and `Comment` in the nemo_action.in files.  The [sample action](https://github.com/linuxmint/nemo/blob/master/files/usr/share/nemo/actions/sample.nemo_action) doesn't include the underscore but the validator is checking for it.  Which one is correct?  Is there any documentation about why this is needed?

**Comment by mdpenguin** [comment]
Never mind: I do see that in the readme.  I think that this should be updated in the sample file.  I'll have an update in a moment.

**Comment by rcalixte** [comment]
> Never mind: I do see that in the readme. I think that this should be updated in the sample file. I'll have an update in a moment.

They are two separate things. Take a look at the Actions installed on your machine. These are slightly different from the Actions in the development process.

**Review by rcalixte — APPROVED** [review]

**Review by claudiux — APPROVED** [review]

**Comment by rcalixte** [comment]
> the issue seems to be that I haven't put an underscore before `Name` and `Comment` in the nemo_action.in files.

These are your first Action contributions. Anything created on your local machine would follow the sample Action. Anything for others and destined for this repository should follow the README.

**Pull request merged**
