### PR TITLE
Add paste-into-file@anaximeno

### PR DESCRIPTION
**Pull request by anaximeno**
TODO:
- [x] Save clip content into a new file
- [x] Append clip content to the end of the file if the file already exists, and the user gave permission for that
- [x] Append content to a if file if one is sent when calling the action (the selected file)
- [x] Test under Wayland

The idea is to create an action where the user can save the clip content inside a new file. If you have ideas of other features that could be nice in this action, just tell me the idea below and I will consider adding it if it seems feasible or adequate to the context of the action.

### CODE REVIEW

**Comment by anaximeno** [comment]
@rcalixte I believe it's ready!

**Comment by anaximeno** [comment]
Wait!

**Comment by anaximeno** [comment]
OK, now it's ready!

**Comment by rcalixte** [comment]
Just a note that you can specify the Selection parameters in the action file so that it only shows the menu for a single file. (It doesn't seem like you intend to support pasting into multiple files, but what about pasting to a new file?)

**Comment by anaximeno** [comment]
> Just a note that you can specify the Selection parameters in the action file so that it only shows the menu for a single file. (It doesn't seem like you intend to support pasting into multiple files, but what about pasting to a new file?)

Yes, I want to only paste into a single file, or a new file if none is selected, but I believe if I choose single it won't work for the case of no file selected.

**Comment by rcalixte** [comment]
> Yes, I want to only paste into a single file, or a new file if none is selected, but I believe if I choose single it won't work for the case of no file selected.

Yeah, it would be great if there were a "0 or 1" option for this use case.

This looks good though! Great job!

**Review by rcalixte — APPROVED** [review]

**Comment by anaximeno** [comment]
Yeah, I agree, thanks!

**Pull request merged**
