### PR TITLE
NEW Advanced IDE Launcher by Adriano Paonessa (@adrianopaonessa) ver. 1.0.0

### PR DESCRIPTION
**Pull request by adrianopaonessa**
# **Advanced IDE Launcher**

Launch you favorite IDE within the current directory.
If more than one IDE is available you can select the one to run.
This is a much flexible and completed version of another action, with new IDEs coming soon based on the requests of the users.

---

## **Available editors**

This is the list of the currently available editors.

- Visual Studio Code
- Visual Studio Code Insiders
- VSCodium
- VSCodium Insiders

## Required things

**You need to have at least one of the editor listed above for the `action` to work and their relative commands ready to use!**

Required commands for each IDE:

- `code` required for Visual Studio Code
- `code-insiders` required for Visual Studio Code Insiders
- `codium` required for VSCodium
- `codium-insiders` required for VSCodium Insiders

### CODE REVIEW

**Comment by FrancescooM** [comment]
Very useful, thank you!

**Comment by rcalixte** [comment]
@adrianopaonessa Have you tested this? It will fail validation as is and I'm not sure that the auxiliary scripts will work as well. Have you considered supporting translations in the user-facing strings as well?

**Comment by adrianopaonessa** [comment]
> @adrianopaonessa Have you tested this? It will fail validation as is and I'm not sure that the auxiliary scripts will work as well. Have you considered supporting translations in the user-facing strings as well?

Yes, i am working to add all the translations and yes, i have tested this with 2 different Linux Mint 22 machines (My laptop with a fresh installation and my desk PC with an older installation updated) and it works fine.

**Comment by rcalixte** [comment]
errors

This is what I saw when testing it.

**Review by rcalixte — APPROVED** [review]

**Pull request merged**
