### PR TITLE
peazip-add-to-archive@xszabo3: update install instructions

### PR DESCRIPTION
**Pull request by xszabo3**
Removed the pictures, if someone knows how to make them work on the Cinnamon Spices website please let me know.
Included steps how to place the missing icons into the correct folder. Is there no way of doing it automatically if the user downloads it from their system?

I was wondering if the name should be updated again. It seems extremely long compared to the other actions on the site.
I was thinking of [actionname] action for Peazip(Flatpak).

### CODE REVIEW

**Comment by rcalixte** [comment]
> Removed the pictures, if someone knows how to make them work on the Cinnamon Spices website please let me know.

Take a look at other Spices. In its simplest form, you can probably use the hyperlink to the GitHub URL at this repository so that they will always be in sync.



> Is there no way of doing it automatically if the user downloads it from their system?

Which icons are you referring to? You can configure the Icon in the Nemo Action file.



> I was wondering if the name should be updated again.

Feel free. It's just the metadata. Once you get it right, it will be easy enough to repeat for the consecutive Actions.

**Review by rcalixte — APPROVED** [review]

**Comment by xszabo3** [comment]
Thank you @rcalixte ! I will add back the pictures.

The action file needs an icon which is specified with Icon-Name= . The flatpak app didn't install any as a theme icon, and it needs a theme icon according to the sample action. The missing icon is solved after dropping the icon in the ~/.local/share/icons folder. So this is only a problem in the case of custom icons.

**Comment by rcalixte** [comment]
> The flatpak app didn't install any as a theme icon

It ships icons but the path is probably in the Flatpak path. Check for something under `/var/lib/flatpak/exports/share/icons`. You can consider creating a symlink and pointing the Icon-Name property to that path. That is much more sustainable long-term in case the icon changes upstream. Test with that locally to make sure that it works.

**Comment by xszabo3** [comment]
The symlink works, thanks again @rcalixte ! The user still needs to move it to the icons folder, but this is definietly a better solution...

**Comment by rcalixte** [comment]
> The user still needs to move it to the icons folder, but this is definietly a better solution...

Not at all actually. You can include the symlink. Just make sure it points to an absolute path. Symlinks are just files that are special pointers elsewhere. It _should_ work like that. 😅

**Comment by rcalixte** [comment]
Hmm. It might not actually be a supported parameter for Icon-Name... This is a hypothesis. I haven't tested it. (On a personal note, this is why I haven't personally created any Actions for Flatpak applications since they can be a bit tricky.)

**Pull request merged**
