### PR TITLE
peazip-add-to-archive@xszabo3: action add to archive for flatpak peazip

### PR DESCRIPTION
**Pull request by xszabo3**
Adds Add to archive for Flatpak Peazip in the context menu.
I tried licensing this correctly, but I'm still not sure if it's correct.

### CODE REVIEW

**Comment by rcalixte** [comment]
@xszabo3 This looks great! One request, since there is already an existing Action for PeaZip, could you rename this to clarify that it is only for the Flatpak version along with indicating it in the metadata so that it is clear when users search from their systems?

**Comment by xszabo3** [comment]
Hi @rcalixte ! Thanks for the quick response! Should I change the UUID as well?

**Comment by rcalixte** [comment]
> Should I change the UUID as well?

Good question... This is uncharted territory but it might be fine for now. (Future me hopes I don't regret this. 😅)

**Comment by rcalixte** [comment]
@xszabo3 Once this is published, you may want to check the Spices website to make sure the images are rendering properly. I suspect that the URLs may need to be updated but we'll see.

**Review by rcalixte — APPROVED** [review]

**Comment by xszabo3** [comment]
Thanks for the heads up @rcalixte . I have 4 more actions incoming. This is why I test thing out on this one first. I need to check how is the github alert ([!IMPORTANT]) rendering too.

**Comment by rcalixte** [comment]
> I need to check how is the github alert ([!IMPORTANT]) rendering too.

This is GitHub-specific syntax so it won't work anywhere that isn't GitHub.



> I have 4 more actions incoming.

Exciting. I noticed the grouping in the documentation and having a group set for users is pretty awesome. Thank you!

**Pull request merged**
